use_frameworks!

platform :ios, '10.0'

target 'TAThirdParty_Example' do
  pod 'TAThirdParty', :path => '../'
  pod 'ThinkingSDK', :path => '/Users/wwango/Desktop/shushucode/ios-sdk'
#  pod 'ThinkingSDK'', '~> 2.8.3'

# 三方
  pod 'AppsFlyerFramework'
  pod 'IronSourceSDK','7.1.8.0'
  pod 'Adjust', '~> 4.29.2'
  pod 'Branch', '~> 1.39.1'
  pod 'AppLovinSDK'
  pod 'AnyThinkiOS'
  pod 'TradPlusAdSDK', '6.9.10'
  pod 'TradPlusAdSDK/TPCrossAdapter', '6.9.10'
  pod 'TradPlusAdSDK/TPADXAdapter', '6.9.10'
  pod 'TradPlusAdSDK/BaiduAdapter', '6.9.10'
  pod 'BaiduMobAdSDK','4.83'



  target 'TAThirdParty_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
