# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'ThirdParty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThirdParty
  pod 'TAThirdParty', :path => '../'
  pod 'ThinkingSDK', '3.0.0'

  ### 三方的库
  pod 'AppsFlyerFramework'
  pod 'IronSourceSDK','7.1.8.0'
  pod 'Adjust', '~> 5.1.0'
  pod 'Branch', '~> 1.39.1'
  pod 'AppLovinSDK'
  pod 'AnyThinkiOS'
  pod 'TradPlusAdSDK', '6.9.10'
  pod 'TradPlusAdSDK/TPCrossAdapter', '6.9.10'
  pod 'TradPlusAdSDK/TPADXAdapter', '6.9.10'
  pod 'TradPlusAdSDK/BaiduAdapter', '6.9.10'
  pod 'BaiduMobAdSDK','4.83'
  pod 'Firebase/Analytics'

end
